# Generated by Django 4.1.2 on 2022-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='id',
        ),
        migrations.AddField(
            model_name='accounts',
            name='bank_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accounts',
            name='ifsc_code',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
