# Generated by Django 4.1.2 on 2022-10-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0002_remove_transactionhistory_id_accounts_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='id',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='acc_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
