# Generated by Django 4.1.2 on 2022-10-30 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0003_remove_accounts_id_alter_accounts_acc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='SMSApp.accounts'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='SMSApp.accounts'),
        ),
    ]
