# Generated by Django 4.1.2 on 2022-10-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0004_alter_transactionhistory_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
